# Generated by Django 3.1 on 2020-09-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200925_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='created',
        ),
    ]
