# Generated by Django 3.1 on 2020-09-28 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tintuc_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
